# fly.toml app configuration file generated for worse-trello-api on 2024-08-26T20:07:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'worse-trello-api'
primary_region = 'otp'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = "local"
  APP_NAME = "Worse Trello API"
  APP_DEBUG = "true"
  APP_TIMEZONE = "UTC"
  APP_URL = "https://worse-trello-api.fly.dev"
  FRONTEND_URL = "https://worse-trello-nuxt.vercel.app"

  APP_LOCALE = "en"
  APP_FALLBACK_LOCALE = "en"
  APP_FAKER_LOCALE = "en_US"

  APP_MAINTENANCE_DRIVER = "file"
  APP_MAINTENANCE_STORE = "database"

  BCRYPT_ROUNDS = "12"

  LOG_CHANNEL = "stack"
  LOG_STACK = "single"
  LOG_DEPRECATIONS_CHANNEL = "null"
  LOG_LEVEL = "debug"

  DB_CONNECTION = "pgsql"

  SESSION_DRIVER = "database"
  SESSION_LIFETIME = "1200"
  SESSION_ENCRYPT = "false"
  SESSION_PATH = "/"
  SESSION_DOMAIN = "null"
  SESSION_SAME_SITE = "none"
  SESSION_SECURE_COOKIE = "true"
  SANCTUM_STATEFUL_DOMAINS = "worse-trello-api.fly.dev"

  GOOGLE_CLIENT_ID="932140321754-6iurefetolu29073k9vlfbgnvh61kr96.apps.googleusercontent.com"
  GOOGLE_REDIRECT_URI="https://worse-trello-api.fly.dev/login/google/callback"

  GITHUB_CLIENT_ID="Ov23lirwnh1jPqUroxxr"
  GITHUB_REDIRECT_URI="https://worse-trello-api.fly.dev/login/github/callback"

  MAIL_MAILER="smtp"
  MAIL_HOST="sandbox.smtp.mailtrap.io"
  MAIL_PORT="2525"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
